### ISSUE TITLE
Setup Travis CI

### ISSUE THREAD

**Issue by upsuper** [sru-systems/rust-argon2#2]
Adding Travis CI integration should be trivial nowadays for a Rust project.

For this repo, you may not want to run tests with debug mode, since they are too slow... Maybe we can just skip the hash tests in debug build while keeping running unit tests in all builds.

**Comment by mrijkeboer** [comment]
I'll take a look at Travis CI when I have some time available.

**Comment by mrijkeboer** [comment]
Commit 7fb0376b386d0f1a4968f1f441c357fce8d0f16e disables the slow hash tests in debug mode.

**Comment by upsuper** [comment]
You don't need to add that to every test function. You can simply add
```rust
#![cfg(not(debug_assertions))]
```
anywhere before the first line of code in that file.

**Comment by upsuper** [comment]
To setup Travis CI, you just need to use an account which can access this repo to sign in Travis CI, and then put a `.travis.yml` with proper content in the root of the repo.

**Comment by upsuper** [comment]
See https://docs.travis-ci.com/user/getting-started

**Comment by mrijkeboer** [comment]
I was already reading that :smile:
