### ISSUE TITLE
New crates.io release

### ISSUE THREAD

**Issue by est31** [sru-systems/rust-argon2#20]
Hi, it would be cool if you could do a new release on crates.io with the new crossbeam version. Thank you! A minor release 0.5.2 would be most prefferable.

**Comment by mrijkeboer** [comment]
Hi @est31 

This crate depends on `crossbeam-utils` of instead of `crossbeam` (since version 0.5.1) and uses the latest version of that crate as far as I can see.

**Comment by est31** [comment]
Oh, I haven't seen 0.5.1. Sorry!
