### ISSUE TITLE
Clarification of field usage in Config struct

### ISSUE THREAD

**Issue by sidju** [sru-systems/rust-argon2#33]
Currently the descriptions are generally no more explanatory than the variable names. Some explanation on what it does with the data or what the intended use is would be good, since your APIs may well be the first a dev sees of argon2. Proposed addition:

Associated data can be used to bind a hash to a specific use case, such as b"development". Can be argued to be redundant with secret and salt, but is a useful additional layer of safety in some cases.

Secret is the usual secret key added to the hashing process. It is highly recommended to set this to randomly generated data to prevent rainbow-table attacks. Losing/changing the servers secret key will of course invalidate all existing password hashes.

Associated data (ad), secret, salt and password are all combined together before hashing. As such they all have more or less the same influence on the resulting hash and a change to any of them will change the hash.

**Comment by mrijkeboer** [comment]
Kindly create a pull request for this.
