### ISSUE TITLE
Make the Config struct self contained, to make Clone meaningful

### ISSUE THREAD

**Issue by sidju** [sru-systems/rust-argon2#35]
Currently doing anything multithreaded or asynchronous with the Config struct requires you to clone and move the ad and secret variables separately. Considering the popularity of async in rust right now it would be beneficial to change the secret and ad variables in Config to Vec<u8>, making the crate easier to use in such situations.

The downsides I can see are that there is one more copy if you are running with static data from the start and that you may store the secret/ad twice.
The benefits I see are that you don't need to bother with internal lifetimes and separate structs, which gives that you can clone the Config and send it to a different thread without additional variables or just place it in an Arc and reuse it forever.

**Comment by mrijkeboer** [comment]
The reason references to the secret and associated data are used, is to enable the caller to have control over this data. This way the caller can erase this sensitive data after computing the hash.

**Comment by sidju** [comment]
With that in mind, though, I can see no difference in security.

If you have a reference and thoroughly delete the sensitive data it refers to you either invalidate the reference, leaving you with a Config that appears to be functional but whose hashes will be invalid, or overwrite the reference first, explicitly doing the same to reduce risk of mistakes.

On the other hand if you have the data stored mutably internally you have access to a Vec which you can still overwrite the data in or explicitly replace with an empty one, only that this will be more clear and more contained.

And in both cases it is probably better for security and code readability to keep a proto-Config with everything except the secret/ad set somewhere that you clone, put the secret/ad in, hash with and delete along with the secret/ad you used. This so that you don't have the same variable as a valid and invalid config depending on point in excecution.

Am I missing something essential here?

**Comment by sidju** [comment]
After some additional digging there are some very exciting ways to try to securely store and securely delete data from memory. None are really at all reasonable for general use at this stage but I can see benefit in allowing the user to wrap the data in their own struct to use them.

However, a fully contained struct would still be nice and helpful for the more general use-case. So creating a ContainedConfig and implementing a Conf trait on both that and the original Config to offer the user a choice would be nice.

**Comment by mrijkeboer** [comment]
Hi @sidju, sorry, I'm not really in favor of creating a `ContainedConfig`.
