### ISSUE TITLE
Documentation(minor): doc comment indentation not rendered in crates.io

### ISSUE THREAD

**Issue by Ben-PH** [sru-systems/rust-argon2#36]
Refer to the three lines of doc comments [here](https://github.com/sru-systems/rust-argon2/blob/804fa18702e3eb753398c226a964500631ed871b/src/lib.rs#L56). They render without indentation as shown [here](https://docs.rs/rust-argon2/0.8.2/argon2/#examples) - see attached image for reference. This is on Firefox 77 and chromium 84.

This has already been reported as an [issue](https://github.com/rust-lang/rust/issues/70732) to the rust-lang repo.

![Here](https://user-images.githubusercontent.com/16680090/85214807-51e6a300-b370-11ea-9b0c-9e6e3ffec254.png)

**Comment by Ben-PH** [comment]
Additional comment: My guess is this is near-zero priority, and can be filed away as "the lang team is on it." Being a passer-by that happened to notice, I wanted to pass it on.

**Comment by mrijkeboer** [comment]
Hi @Ben-PH, as you already suggested I'll close this with "the lang team is on it."
