### ISSUE TITLE
[Question/Documentation Request] How long should the seed be? 

### ISSUE THREAD

**Issue by john01dav** [sru-systems/rust-argon2#40]
This library looks to have exactly what I need, but in order to use it I need to pick a seed length (generating the seed seems easy enough via `OsRng::fill_bytes` in the `rand` crate). I'm no security expert, so I'm not really qualified to pick this length myself, and the documentation doesn't give any useful recommendations. As such, I'm wondering what it should be.

**Comment by Lireer** [comment]
Citing the "Recommended parameters" section from [the paper](https://www.password-hashing.net/argon2-specs.pdf):
"Select the salt length.  128 bits is sufficient for all applications, but can be reduced to 64 bits in the case of space constraints."
