### ISSUE TITLE
`Memory::as_lanes_mut` is unsound

### ISSUE THREAD

**Issue by kazcw** [sru-systems/rust-argon2#41]
[&mut must not alias](https://doc.rust-lang.org/nomicon/references.html). The [current implementation](https://github.com/sru-systems/rust-argon2/blob/7a15286927b9e808480bd6e2ad7c64bc543ab849/src/memory.rs#L38) relies on UB.

`as_lanes_mut` is impossible to implement soundly, but it's not necessary; the `unsafe` boundary is in the wrong place. [`fill_segment`](https://github.com/sru-systems/rust-argon2/blob/7a15286927b9e808480bd6e2ad7c64bc543ab849/src/core.rs#L229) should be an `unsafe fn`, since a data race could be caused by calling it with the wrong parameters. It can take a `*mut Memory` as an argument (with a `Send` wrapper).

**Comment by mrijkeboer** [comment]
Hi @kazcw, thanks for bringing this up. Would you mind creating all pull request for this?
