### ISSUE TITLE
make core module public?

### ISSUE THREAD

**Issue by Ragnaroek** [sru-systems/rust-argon2#44]
I'm currently implementing RandomX for Monero in Rust (https://github.com/Ragnaroek/mithril). For this
I need the functions `initialize` and `fill_memory_blocks` from `core` to directly initialize the seed memory with argon2 hashes.

What are your thoughts about making the core public usable from the outside for "advanced usage"?

**Comment by Ragnaroek** [comment]
Any thoughts on that?

**Comment by mrijkeboer** [comment]
Hi @Ragnaroek,

Sorry, I'm not in favor of making the core module public.
