### ISSUE TITLE
Follow RFC 9106 recommendations for `Config::default()` 

### ISSUE THREAD

**Issue by ShE3py** [sru-systems/rust-argon2#50]
Hi,

[`Config::default()`](https://github.com/sru-systems/rust-argon2/blob/583c98c2c91b5dc2496265f216b0d5083269b02a/src/config.rs#L69) currently uses Argon2i with t=3 and 4 MiB of memory, while RFC 9106 recommends Argon2id with 64 MiB of memory as second-best choice; https://datatracker.ietf.org/doc/html/rfc9106#name-recommendations.

**Comment by mrijkeboer** [comment]
Hi @ShE3py,

Thanks for logging this  issue. This library uses the same defaults as the original [C implementation](https://github.com/P-H-C/phc-winner-argon2/tree/master). However, I added `Config.rfc9106()` and `Config.rfc9106_low_mem()` in f4c6c65 to accommodate for this.
